### ISSUE TITLE
[Button] Crash with NS7 on Android

### ISSUE THREAD

**Issue by andreacappadona17** [nativescript-community/ui-material-components#175]
### Which platform(s) does your issue occur on?
- Android 
- Android versions: 9 and 10
- emulator or device. What type of device?
Emulator and device Huawei P20 Lite

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.8
- Cross-platform modules: 7.0.3
- Runtime(s): Android: 7.0.0
- Plugin(s): 
"@nativescript-community/ui-material-activityindicator": "4.0.11",
    "@nativescript-community/ui-material-button": "4.0.11",
    "@nativescript-community/ui-material-cardview": "4.0.11",
    "@nativescript-community/ui-material-core": "4.0.11",
    "@nativescript-community/ui-material-dialogs": "4.0.11",
    "@nativescript-community/ui-material-floatingactionbutton": "4.0.11",
    "@nativescript-community/ui-material-progress": "4.0.11",
    "@nativescript-community/ui-material-textfield": "4.0.11",
    "@nativescript-community/ui-material-textview": "4.0.11",
    "@nativescript/core": "~7.0.3",
    "@nativescript/fingerprint-auth": "7.0.0",
    "@nativescript/iqkeyboardmanager": "2.0.0",
    "@nativescript/theme": "~2.5.0",
    "@nstudio/nativescript-loading-indicator": "4.0.0",

- Dev:
"@nativescript/android": "7.0.0",
    "@nativescript/ios": "7.0.0",
    "@nativescript/types": "~7.0.3",
    "@nativescript/webpack": "~3.0.4",
    "@typescript-eslint/eslint-plugin": "^4.0.1",
    "@typescript-eslint/parser": "^4.0.1",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.8.1",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-prettier": "^3.1.4",
    "nativescript": "7.0.8",
    "pre-commit": "^1.2.2",
    "prettier": "2.1.1",
    "typescript": "3.9.7"

### Please, tell us how to recreate the issue in as much detail as possible. 
Add a Material Button to one xml page.

Navigating to that page will crash the app. No matter what variant I set for the button, it will always crash.

This part of the code always sets layoutId to 0, which I think could be the issue.
https://github.com/nativescript-community/ui-material-components/blob/92a98ce5428b581dfccb2255c468867796d66ced/src/button/button.android.ts#L23-L44

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: android.content.res.Resources$NotFoundException: Resource ID #0x0
System.err: 
System.err: StackTrace:
System.err: createNativeView(file: node_modules/@nativescript-community/ui-material-button/button.android.js:39:0)
System.err:     at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:525:0)
System.err:     at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:567:0)
System.err:     at eachChildView(file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:101:0)
System.err:     at eachChild(file: node_modules/@nativescript/core/ui/core/view/view-common.js:700:0)
System.err:     at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:566:0)
System.err:     at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:567:0)
System.err:     at eachChildView(file: node_modules/@nativescript/core/ui/content-view/index.js:65:0)
System.err:     at eachChild(file: node_modules/@nativescript/core/ui/core/view/view-common.js:700:0)
System.err:     at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:566:0)
System.err:     at (file: node_modules/@nativescript/core/ui/core/view-base/index.js:567:0)
System.err:     at eachChildView(file: node_modules/@nativescript/core/ui/content-view/index.js:65:0)
System.err:     at eachChildView(file: node_modules/@nativescript/core/ui/page/page-common.js:99:0)
System.err:     at eachChild(file: node_modules/@nativescript/core/ui/core/view/view-common.js:700:0)
System.err:     at _setupUI(file: node_modules/@nativescript/core/ui/core/view-base/index.js:566:0)
System.err:     at _addViewCore(file: node_modules/@nativescript/core/ui/core/view-base/index.js:429:0)
System.err:     at _addView(file: node_modules/@nativescript/core/ui/core/view-base/index.js:418:0)
System.err:     at onCreateView(file: node_modules/@nativescript/core/ui/frame/index.android.js:738:0)
System.err:     at onCreateView(file: node_modules/@nativescript/core/ui/frame/fragment.android.js:25:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
System.err:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
System.err:     at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
System.err:     at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
System.err:     at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
System.err:     at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
System.err:     at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
System.err:     at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
System.err:     at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
System.err:     at android.os.Handler.handleCallback(Handler.java:907)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     at android.os.Looper.loop(Looper.java:216)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7625)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
System.err: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
System.err:     at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:292)
System.err:     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2390)
System.err:     at android.content.res.Resources.getLayout(Resources.java:1341)
System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
System.err:     ... 26 more
```

### Is there any code involved? 
`<mdb:Button class="login-button" text="Login" tap="{{ login }}" />`

**Comment by farfromrefug** [comment]
@andreacappadona17 this usually means resources are missing.
Could you try to remove `node_modules`, `hooks`, `platforms` then build again?

**Comment by andreacappadona17** [comment]
I worked after removing `node_modules`, `hooks` and `platforms`, thanks!
