### ISSUE TITLE
In Android i get errors with Material Textfield, in tns run android it gives many errors and when build interface is broken

### ISSUE THREAD

**Issue by NavruzbekNoraliev** [nativescript-community/ui-material-components#227]
**tns version: 7.1.2**

  **"@nativescript/android": "7.0.0",
    "@nativescript/ios": "7.1.0",**

I used material 
npm i --save @nativescript-community/ui-material-textview

<MDTextView  helper="example helper" placeholderColor="green" keyboardType="datetime"
        hint="i am an hint" returnKeyType="next" (focus)="onFocus($event)" (blur)="onBlur($event)"
        (textChange)="onTextChange($event)"></MDTextView>

Almost Everything is done as in docs, but it cant render properly

**Comment by farfromrefug** [comment]
can't really help without any log.

**Comment by NavruzbekNoraliev** [comment]
it just doesnot show mat input fields 

and many warnings while building  
WARNING in ../node_modules/@nativescript-community/ui-material-textfield/textfield.js 251:78-96
"export 'getVerticalGravity' was not found in '@nativescript-community/ui-material-core/android/utils'
 @ ../node_modules/@nativescript-community/ui-material-textfield/angular/fesm2015/nativescript-community-ui-material-textfield-angular.js
 @ ./app/components/login/login.module.ts
 @ ./app/app-routing.module.ts
 @ ./app/app.module.ts
 @ ./main.ts
[
![Screenshot_1611638380](https://user-images.githubusercontent.com/44977644/105813630-f51c2c80-5fd1-11eb-9f66-360e29fbfa62.png)
](url)

**Comment by NavruzbekNoraliev** [comment]
**Log says:** 
An uncaught Exception occurred on "main" thread.
Attempt to invoke virtual method 'void android.view.View.bringToFront()' on a null object reference

StackTrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.bringToFront()' on a null object reference
	at com.telerik.android.primitives.widget.sidedrawer.transitions.SlideInOnTopTransition.setProgressRight(SlideInOnTopTransition.java:76)
	at com.telerik.android.primitives.widget.sidedrawer.transitions.DrawerTransitionBase.setProgress(DrawerTransitionBase.java:93)
	at com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer.handleOnUp(RadSideDrawer.java:492)
	at com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer.onGesture(RadSideDrawer.java:447)
	at com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer.onInterceptTouchEvent(RadSideDrawer.java:435)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2664)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
	at android.view.View.dispatchPointerEvent(View.java:14568)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by farfromrefug** [comment]
@NavruzbekNoraliev look at your log the crash is in the ui sidedrawer plugin
