### ISSUE TITLE
[MDTextField][Angular] (ANDROID) :  Calling js method on CreateView Failed

### ISSUE THREAD

**Issue by NavruzbekNoraliev** [nativescript-community/ui-material-components#228]
### Which platform(s) does your issue occur on?
- Android 
- Android version: 11
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.1.2
- Cross-platform modules: version:  7.0.9,
- tns-android and tns-ios properties does not exist in the `package.json` file
- Plugin(s):
```
  "dependencies": {
    "@angular/animations": "~11.0.0",
    "@angular/common": "~11.0.0",
    "@angular/compiler": "~11.0.0",
    "@angular/core": "~11.0.0",
    "@angular/forms": "~11.0.0",
    "@angular/platform-browser": "~11.0.0",
    "@angular/platform-browser-dynamic": "~11.0.0",
    "@angular/router": "~11.0.0",
    "@nativescript-community/ui-material-textfield": "^5.2.3",
    "@nativescript/angular": "~11.0.0",
    "@nativescript/core": "~7.1.0",
    "@nativescript/theme": "~3.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.0.0",
    "@nativescript/android": "7.0.1",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~4.0.0",
    "@ngtools/webpack": "~11.0.0",
    "typescript": "~4.0.0"
  },
```

### To reproduce it:
used everything as the documentation says, even created a separate project to test it, but still give an error, so there is no library collision

```
An uncaught Exception occurred on "main" thread.
Calling js method onCreateView failed
Error: android.view.InflateException: Binary XML file line #18 in org.nativescript.DemoMaterial:layout/material_text_field_filled: Binary XML file line #18 in org.nativescript.DemoMaterial:layout/material_text_field_filled: Error inflating class com.google.android.material.textfield.TextInputLayout

StackTrace:
createNativeView(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:93895:53)
	at _setupUI(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:118776:31)
	at (file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:118816:19)
	at eachChildView(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:129435:28)
	at eachChild(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:120975:14)
	at _setupUI(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:118815:14)
	at (file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:118816:19)
	at eachChildView(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:129435:28)
	at eachChild(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:120975:14)
	at _setupUI(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:118815:14)
	at (file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:118816:19)
	at eachChildView(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:116355:13)
	at eachChildView(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:130864:15)
	at eachChild(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:120975:14)
	at _setupUI(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:118815:14)
	at _addViewCore(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:118680:18)
	at _addView(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:118669:14)
	at onCreateView(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:125228:19)
	at onCreateView(file:///data/data/org.nativescript.DemoMaterial/files/app/vendor.js:123088:40)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.view.InflateException: Binary XML file line #18 in org.nativescript.DemoMaterial:layout/material_text_field_filled: Binary XML file line #18 in org.nativescript.DemoMaterial:layout/material_text_field_filled: Error inflating class com.google.android.material.textfield.TextInputLayout
Caused by: android.view.InflateException: Binary XML file line #18 in org.nativescript.DemoMaterial:layout/material_text_field_filled: Error inflating class com.google.android.material.textfield.TextInputLayout
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:657)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
	at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
	at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:217)
	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:145)
	at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:115)
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:460)
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:419)
	... 34 more

```
### Code Below in Attachaments
[DemoMaterial.zip](https://github.com/nativescript-community/ui-material-components/files/5872578/DemoMaterial.zip)

**Comment by farfromrefug** [comment]
@NavruzbekNoraliev the error is in the log:
```
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).

```

**Comment by NavruzbekNoraliev** [comment]
I shared error myself) I dont ask for error, I'm asking how to solve it(

**Comment by farfromrefug** [comment]
@NavruzbekNoraliev you did not ask for help you posted a bug report. very different. if you have question it would be best to ask first on slack. I would be happy to help you. 
I answered that way here because it is not a bug and a usual android error. I pointed the error so that you could search for yourself.
now that being said you need to change your android app style like explained here https://medium.com/over-engineering/setting-up-a-material-components-theme-for-android-fbf7774da739

**Comment by NavruzbekNoraliev** [comment]
I know that it is an android error,  but it is being raised while compiling native script to an android file, I think it should be solved with native script code, somewhere in config or other. thanks for your answer. I did not find it useful. My issue still remains open as it is a bug, others who want to answer first create a new project with a native script and material text field, you will understand what is happening

**Comment by farfromrefug** [comment]
@NavruzbekNoraliev you don't understand how it works. it is not a N issue. it is an android issue. please move this to slack If you Ned more help

**Comment by NavruzbekNoraliev** [comment]
Ok send me a slack invite, coz i cant  login to nativescript community slack
