### ISSUE TITLE
TabContentItem on MDTabs error setAttribute

### ISSUE THREAD

**Issue by vallemar** [nativescript-community/ui-material-components#257]
### Which platform(s) does your issue occur on?
- Android only test
- Android 10 (only test)
- emulator/device. Both

### Please, provide the following version numbers that your issue occurs with:

- CLI:  8.0.0
√ Component nativescript has 8.0.0 version and is up to date.
√ Component @nativescript/core has 8.0.0 version and is up to date.
√ Component @nativescript/ios has 8.0.0 version and is up to date.
√ Component @nativescript/android has 8.0.0 version and is up to date.

I have migrated my application vue to NS 8 (I don't know if it has something to do with it) the question is that if I change `Tabs `to `MDTabs `and keep `TabContentItem` as stated in the plugin documents I have the error:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{com.vallemar.checkpointcurly/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'setAttribute' of undefined
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vallemar.checkpointcurly/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'setAttribute' of undefined
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:223)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'setAttribute' of undefined
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:29)
System.err:     at android.app.Activity.performCreate(Activity.java:8000)
System.err:     at android.app.Activity.performCreate(Activity.java:7984)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
System.err:     ... 11 more

```

When I change `TabContentItem` to `MDTabContentItem` everything works fine

**Comment by farfromrefug** [comment]
@vallemar always use `MDTabContentItem ` if using `MDTabs`

**Comment by vallemar** [comment]
@farfromrefug  here it says the opposite  https://github.com/nativescript-community/ui-material-components/blob/master/packages/tabs/README.md

**Comment by farfromrefug** [comment]
@vallemar then the doc is not up to date.
