### ISSUE TITLE
[Tabs] [Android]: App gets crashed when it is running in background and Phone font size is changed

### ISSUE THREAD

**Issue by NathanWalker** [nativescript-community/ui-material-components#260]
*Transfer from core*
Original reporter @rmn81

**Describe the bug**
App gets crashed when it is running in background and Phone font size is changed. It is happening only when selectedItemColor property is applied on TabStrip. It is happing on android not sure about iOS.

**Error:**
`[ba7898cd]: An uncaught Exception occurred on "main" thread.
Calling js method onStart failed
TypeError: Cannot read property 'setTextColor' of null

StackTrace:
Tabs._setItemColor(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/tabs/tabs.js:608:42)
at (file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/tabs/tabs.js:477:19)
at Tabs.setTabStripItems(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/tabs/tabs.js:474:15)
at Tabs.<computed>(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/tabs/tabs.js:680:14)
at applyAllNativeSetters(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/properties/properties.js:1048:28)
.............................................................
............................................................`

**Sample project**
 [Playground](https://play.nativescript.org/?template=play-ng&id=1El8Ii)

**Additional context**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/14125731/109960056-483e7900-7d0e-11eb-896c-07c0d24e8d57.gif)

**Comment by farfromrefug** [comment]
@NathanWalker i cant reproduce it here on api 29. I did a release with fixes, Could you test and report what version it crashes on?

**Comment by rmn81** [comment]
@farfromrefug Tested on API 29. it is still breaking.

Versions:
nativescript: NS7(7.0.11)
@nativescript/core: 7.1.4
@nativescript/android: 7.0.1

**Comment by farfromrefug** [comment]
@rmn81 what plugin version? That s what i need to know

**Comment by rmn81** [comment]
@farfromrefug I am not sure for which plugin you want to know the version. Below is the content of my package.json(you can also check the playground sample mentioned in the Description)

{
  "name": "@nativescript/template-hello-world-ts",
  "main": "app.js",
  "version": "7.0.6",
  "author": "NativeScript Team <oss@nativescript.org>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "keywords": [
    "nativescript",
    "mobile",
    "{N}",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "homepage": "https://github.com/NativeScript/nativescript-app-templates",
  "dependencies": {
    "@nativescript/core": "~7.1.0",
    "@nativescript/theme": "~2.3.0"
  },
  "devDependencies": {
    "@nativescript/android": "7.0.1",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~4.0.0",
    "typescript": "~3.9.0"
  },
  "private": "true",
  "readme": "NativeScript Application"
}

**Comment by farfromrefug** [comment]
@rmn81 i dont understand you dont even use @nativescript-community/ui-material-tabs ? it might.mean that issue already existed in N Tab component ? @NathanWalker I am lost here. (though I fixed the issue in latest release)

**Comment by farfromrefug** [comment]
@NathanWalker this one should be fixed
