### ISSUE TITLE
Can't get the demo to work

### ISSUE THREAD

**Issue by Whip** [nativescript-community/ui-material-components#311]
### Which platform(s) does your issue occur on?
- Android 10, Real device

### Please, tell us how to recreate the issue in as much detail as possible. 
I downloaded the code from this repo and ran the demo (plain js) app. I got the following errors:

```
ERROR in /Users/vipulk/Documents/MaterialDemo/tsconfig.json
[tsl] ERROR
      TS6053: File '../tsconfig' not found.

ERROR in ./app.ts
Module build failed (from ../node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
    at Object.loader (/Users/vipulk/Documents/MaterialDemo/node_modules/ts-loader/dist/index.js:19:18)

ERROR in ../tsconfig.json
TS6053: File '../tsconfig' not found.
```

and then after Gradle build
```
Error executing Static Binding Generator: Couldn't find '/Users/vipulk/Documents/MaterialDemo/platforms/android/build-tools/sbg-bindings.txt' bindings input file. Most probably there's an error in the JS Parser execution. You can run JS Parser with verbose logging by executing "node '/Users/vipulk/Documents/MaterialDemo/platforms/android/build-tools/jsparser/js_parser.js' enableErrorLogging".
```
Upon executing the suggested command, nothing happens and retrying produces same error.

**Comment by farfromrefug** [comment]
@Whip the demo code depends on the whole repo structure. Seeing your logs you only extracted the demo from the repo. It wont work.

**Comment by Whip** [comment]
My bad. Okay I've included the entire repo. Navigated to demo folder
`cd demo`
`ns run android`

I get this:
```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/vipulk/Documents/Material-Components/packages/core
npm ERR! command failed
npm ERR! command sh -c node postinstall.js
npm ERR! internal/modules/cjs/loader.js:883
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module '/Users/vipulk/Documents/Material-Components/packages/core/postinstall.js'
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
npm ERR!     at internal/main/run_main_module.js:17:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vipulk/.npm/_logs/2021-06-28T10_07_56_038Z-debug.log
Unable to install dependencies. Make sure your package.json is valid and all dependencies are correct. Error is: Command npm failed with exit code 1
```

I've attached the log file mentiond as well.
[2021-06-28T10_07_56_038Z-debug.log](https://github.com/nativescript-community/ui-material-components/files/6725400/2021-06-28T10_07_56_038Z-debug.log)

Sorry if I'm still being a noob.

**Comment by farfromrefug** [comment]
@Whip you need to build the project first. The demo is made to show you code. However it is also meant for us to develop with. So it relies on local built project. See the last question of the faq https://github.com/nativescript-community/ui-material-components#faq

**Comment by Whip** [comment]
It still didn't work. The error I'm getting is 
```
Cannot find module '@nativescript-community/ui-material-core/scripts/before-prepare.js'
Require stack:
- /Users/vipulk/Documents/Material-Components/demo/hooks/before-prepare/nativescript-community-ui-material-core.js
- /usr/local/lib/node_modules/nativescript/lib/common/services/hooks-service.js
- /usr/local/lib/node_modules/nativescript/lib/common/yok.js
- /usr/local/lib/node_modules/nativescript/lib/bootstrap.js
- /usr/local/lib/node_modules/nativescript/lib/nativescript-cli.js
- /usr/local/lib/node_modules/nativescript/bin/tns
```
This happens on the last step `npm run demo.android`. I had setup a fresh copy of the repo for running the commands you linked.

**Comment by farfromrefug** [comment]
@Whip ok i know what s going on! will fix it and push right away

**Comment by farfromrefug** [comment]
@Whip i pushed a fix and updated the readme. Instead of running `npm run tsc` you need to run `npm run build.all`

**Comment by Whip** [comment]
Worked. Thanks for all your support
