### ISSUE TITLE
Crash on android when ui-material-bottom-navigation is used alongside nativescript-inappbrowser plugin

### ISSUE THREAD

**Issue by JonasSchrouff** [nativescript-community/ui-material-components#321]
### Which platform(s) does your issue occur on?
- Android (tested on Android 9)

### Please, provide the following version numbers that your issue occurs with:
- CLI: 8.0.2
- Cross-platform modules: 8.0.8
- Runtime(s): 8.0.8
- Plugin(s):  
```
...
"@nativescript-community/ui-material-bottom-navigation": "^5.3.10",
"nativescript-inappbrowser": "^3.0.2",
...
```

My app crashes when ever I try to open the inAppBrowser (via mentioned plugin).
The error however is triggered by code of the ui-material-bottom-navigation plugin. I get the error message "TypeError: activity.getLifecycle is not a function". Here is the stacktrace:
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onViewAttachedToWindow failed
System.err: TypeError: activity.getLifecycle is not a function
System.err:
System.err: StackTrace:
System.err: (file: app\webpack:\my-app\app\app.js:166:0)
System.err:     at _handleEvent(file: app\webpack:\my-app\node_modules\@nativescript\core\data\observable\index.js:233:0)
System.err:     at notify(file: app\webpack:\my-app\node_modules\@nativescript\core\data\observable\index.js:216:0)
System.err:     at global.__onDiscardedError(file: app\webpack:\my-app\node_modules\@nativescript\core\application\application-common.js:146:0)
System.err:     at com.tns.Runtime.passExceptionToJsNative(Native Method)
System.err:     at com.tns.Runtime.passDiscardedExceptionToJs(Runtime.java:91)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1307)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.gen.java.lang.Object_vendor_177_28_AttachListener.onViewAttachedToWindow(Object_vendor_177_28_AttachListener.java:18)
System.err:     at android.view.View.dispatchAttachedToWindow(View.java:18358)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3397)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
System.err:     at android.view.ViewGroup.addViewInner(ViewGroup.java:5077)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4865)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4805)
System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4778)
System.err:     at android.view.ViewOverlay$OverlayViewGroup.add(ViewOverlay.java:205)
System.err:     at android.view.ViewGroupOverlay.add(ViewGroupOverlay.java:72)
System.err:     at androidx.transition.ViewGroupOverlayApi18.add(ViewGroupOverlayApi18.java:48)
System.err:     at androidx.transition.Visibility.onDisappear(Visibility.java:428)
System.err:     at androidx.transition.Visibility.createAnimator(Visibility.java:257)
System.err:     at androidx.transition.Transition.createAnimators(Transition.java:747)
System.err:     at androidx.transition.TransitionSet.createAnimators(TransitionSet.java:480)
System.err:     at androidx.transition.Transition.playTransition(Transition.java:1821)
System.err:     at androidx.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:301)
System.err:     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2474)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:761)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:696)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

The issue seems to be that `ui-material-components/src/bottom-navigation/index.android.ts` tries to access the function `getLifecycle()` on an activity. This function might not be defined in every situation.
Here is the code which triggers the error:
```
// _onAttachedToWindow called from OS again after it was detach
// still happens with androidx.fragment:1.3.2
const activity = Application.android.foregroundActivity;
if ((this._manager && this._manager.isDestroyed()) || !activity.getLifecycle().getCurrentState().isAtLeast(androidx.lifecycle.Lifecycle.State.STARTED)) {
    return;
}
```

https://github.com/nativescript-community/ui-material-components/blob/ed6bbaf2f3d3427610052daab5b7243030f07671/src/bottom-navigation/index.android.ts#L406

**Comment by farfromrefug** [comment]
@JonasSchrouff I will push a fix, however could you try to modify `node_modules/nativescript-inappbrowser/ChromeTabsManagerActivity.js` and replacea `android.appActivity` with `androidx.fragment.app.FragmentActivity` ? make the change, remove the platforms folder and run it again.
thanks

**Comment by JonasSchrouff** [comment]
@farfromrefug Thanks for your quick reply. Unfortunately the quick fix you suggested does not seem to work for me. I still get the same error after doing the change & removing platform folder.

**Comment by farfromrefug** [comment]
@JonasSchrouff ok really weird. Could you try and create an easy reproducible sample project?

**Comment by JonasSchrouff** [comment]
@farfromrefug Your update has fixed the issue. Thank you very much!
