### ISSUE TITLE
Getting error: "Type passed in is not NgModuleType" when importing the card

### ISSUE THREAD

**Issue by YonatanKra** [nativescript-community/ui-material-components#333]
### Which platform(s) does your issue occur on?
- Android/iOS
- All
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.1.2

### Please, tell us how to recreate the issue in as much detail as possible. 
1) Created a new nativescript-angular app
2) Installed the card component
3) Imported it as a module inside one of my modules

I get this error on Android:

```
An uncaught Exception occurred on "main" thread.
Unable to start activity ComponentInfo{org.nativescript.dragonsandcoin/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: ASSERTION ERROR: Type passed in is not NgModuleType, it does not have 'ɵmod' property.

StackTrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.dragonsandcoin/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: ASSERTION ERROR: Type passed in is not NgModuleType, it does not have 'ɵmod' property.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
Error: ASSERTION ERROR: Type passed in is not NgModuleType, it does not have 'ɵmod' property.
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:29)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
	... 11 more
```

What might be the problem?

**Comment by farfromrefug** [comment]
@YonatanKra you should ask on discord you would get better angular help
