### ISSUE TITLE
Bottom navigation on change mode theme break app 

### ISSUE THREAD

**Issue by vallemar** [nativescript-community/ui-material-components#343]
When I change the theme of my mobile between light and dark and I enter my application I have the following error:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onStart failed
System.err: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.LinearLayout.getChildAt(int)' on a null object reference
System.err:
System.err: StackTrace:
System.err: updateAndroidItemAt(file: app\webpack:\freqtrade\node_modules\@nativescript-community\ui-material-bottom-navigation\index.android.js:655:0)
System.err:     at (file: app\webpack:\freqtrade\node_modules\@nativescript-community\ui-material-bottom-navigation\index.android.js:677:0)
System.err:     at updateTabStripItems(file: app\webpack:\freqtrade\node_modules\@nativescript-community\ui-material-bottom-navigation\index.android.js:674:0)
System.err:     at setTabBarBackgroundColor(file: app\webpack:\freqtrade\node_modules\@nativescript-community\ui-material-bottom-navigation\index.android.js:671:0)
System.err:     at [backgroundColor:setNative](file: app\webpack:\freqtrade\node_modules\@nativescript-community\ui-material-core\tab-navigation-base\tab-strip\index.js:64:0)
System.err:     at applyPendingNativeSetters(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\properties\index.js:1117:0)
System.err:     at initNativeView(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\properties\index.js:1076:0)
System.err:     at onResumeNativeUpdates(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:737:22)
System.err:     at _resumeNativeUpdates(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:280:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:235:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view\index.android.js:309:0)
System.err:     at (file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
System.err:     at callLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChild(file: app\webpack:\freqtrade\node_modules\@nativescript-community\ui-material-core\tab-navigation-base\tab-navigation-base\index.js:39:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view\index.android.js:309:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript-community\ui-material-bottom-navigation\index.android.js:288:0)
System.err:     at (file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
System.err:     at callLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChildView(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view\view-common.js:759:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view\index.android.js:309:0)
System.err:     at (file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
System.err:     at callLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChildView(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view\view-common.js:759:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view\index.android.js:309:0)
System.err:     at (file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
System.err:     at callLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChildView(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\content-view\index.js:65:0)
System.err:     at eachChildView(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\page\page-common.js:106:0)
System.err:     at eachChild(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view\view-common.js:759:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view\index.android.js:309:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\page\index.android.js:38:0)
System.err:     at (file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
System.err:     at callLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChildView(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\frame\frame-common.js:435:0)
System.err:     at eachChild(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view\view-common.js:759:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view\index.android.js:309:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\frame\frame-common.js:90:0)
System.err:     at onLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\frame\index.android.js:198:0)
System.err:     at (file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
System.err:     at callLoaded(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at onStart(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\frame\index.android.js:977:0)
System.err:     at onStart(file: app\webpack:\freqtrade\node_modules\@nativescript\core\ui\frame\activity.android.js:30:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:39)
System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1447)
System.err:     at android.app.Activity.performStart(Activity.java:8144)
System.err:     at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3922)
System.err:     at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
System.err:     at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
System.err:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
System.err:     at android.os.Looper.loop(Looper.java:219)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:8393)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.LinearLayout.getChildAt(int)' on a null object reference
System.err:     at com.nativescript.material.core.BottomNavigationBar.updateItemAt(BottomNavigationBar.java:122)
System.err:     ... 21 more
```

I share the code with you privately as it is a private project. Although I think it is nothing of my APP and is general of the component.
I have taken a look where it fails, I have changed a few things but I have not found the problem.

**Comment by farfromrefug** [comment]
@vallemar it is fixed in the code but i cant release right because of angular...
Will have to drop angular for now.

**Comment by vallemar** [comment]
Ah ok perfect, good to know that the problem is located! thank you @farfromrefug

**Comment by farfromrefug** [comment]
@vallemar just released 6.2.4

**Comment by vallemar** [comment]
@farfromrefug  you're amazing

**Comment by vallemar** [comment]
@farfromrefug Is it fixed, do I close this issue or leave it open to track down the angular issue?

**Comment by farfromrefug** [comment]
@vallemar we can close it it is unrelated
